### ISSUE TITLE
Can we have the option to provide the SourceFileMap option in Launch.json

### ISSUE THREAD

**Issue by preetipadalia** [getgauge/gauge-vscode#436] opened 2020-05-22 10:40 UTC
To Debug an external code from a different assembly how can we provide the source file option in gauge. 
In Launch.json following is the way we can provide that option:
 "sourceFileMap": {
                "<insert-source-path-here>": "<insert-target-path-here>"
            }

This Option will really be very helpful.

Thanks

**Comment by zabil** [comment] 2020-06-08 12:15
This should be an IDE feature. Have you tried configuring source maps according to https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#source-file-map ?

**Comment by preetipadalia** [comment] 2020-06-08 12:27
@zabil We can do this setting for other projects but Gauge project debugging happens through Gauge Extension in VSCode. The extension have the debbug configuration hardcoded inside, so even if we add these values in launch.json it will not be picked.

**Comment by sriv** [comment] 2020-07-08 10:33
@preetipadalia - since you've put in effort to find the cause, would you be interested in submitting a fix?

**Comment by preetipadalia** [comment] 2020-07-08 10:48
Yeah sure I would love to.. I have done changes in my local. Will push the
changes.

**Comment by BugDiver** [comment] 2020-07-16 05:47
This is fixed via #441

**Closed by BugDiver** 2020-07-16 05:47 UTC
