### ISSUE TITLE
Format Document removes needed text from tables

### ISSUE THREAD

**Issue by kuechlerm** [getgauge/gauge-vscode#294] opened 2018-10-07 13:58 UTC
Verion 0.0.7

If I run "Format Document" a table gets formatted.
Unfortunately it also removes needed characters:

- Leading whitespace
- | 
- \

This leads to the following text change:

```
|Line|Content|
|----|----|
|0   |   abc \| xyz     |
```
Changes to (first formatting):
```
|Line|Content  |
|----|---------|
|0   |abc | xyz|
```
And then to (second formatting):
```
|Line|Content|
|----|-------|
|0   |abc    |
```

I can live with the removal of whitespace, because I can wrap the Text in "text".
But the removal of \ and | is a real problem.

**Comment by NivedhaSenthil** [comment] 2018-10-09 05:12
@kuechlerm Thanks for reporting, we looking for the fix.

**Comment by peaceiswithislam** [comment] 2018-12-17 11:32
The problem is with Github itself as it recognises markdown,I would suggest typing this type of code

> |Line|Content|
> |---- |-------|----
> |0 |abc [\]|xyz

**Comment by peaceiswithislam** [comment] 2018-12-17 11:33
The problem is with Github itself as it recognises markdown,I would suggest typing this type of code

|Line|Content|
|---- |-------|----
|0 |abc \*\|xyz

**Comment by peaceiswithislam** [comment] 2018-12-17 11:34
The problem is with Github itself as it recognises markdown,I would suggest typing this type of code

|Line|Content|
|---- |-------|----
|0 |abc *\*\|xyz

**Comment by zabil** [comment] 2020-11-23 10:07
Closing this as this is tracked at https://github.com/getgauge/gauge/issues/318

**Closed by zabil** 2020-11-23 10:07 UTC
