### ISSUE TITLE
Run and Debug options missing from Spec file

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge-vscode#363] opened 2019-04-02 19:23 UTC
**Expected**
User should get Run and Debug options from spec file

**Actual** 
User is not getting Run and Debug options from spec file

**Steps to reproduce**
This is happening with VS Code version 1.32.3 and Gauge VSCode plugin version 0.0.9

**Gauge Versions**
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
dotnet (0.1.2.nightly-2019-02-14)
html-report (4.0.7)
screenshot (0.0.1)

**Comment by sriv** [comment] 2019-04-03 01:15
hi @manavghaigithub - I am unable to see this behaviour on Ubuntu using the same version of vscode, gauge-vscode and gauge that you have listed.

What OS are you on?

**Comment by manavghaigithub** [comment] 2019-04-03 01:17
Srikanth - I am on Windows 10

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sriv** [comment] 2019-04-03 01:32
Thanks, I'll try it on win10. In the meantime, can you see if downgrading the gauge-vscode plugin to 0.0.8 helps? You can get the installer from https://github.com/getgauge/gauge-vscode/releases/tag/v0.0.8

**Comment by manavghaigithub** [comment] 2019-04-03 01:35
Srikanth - I tried to downgrade but unfortunately I am getting message that 0.0.8 is not supported by VSCode 1.32.X so it’s not letting me install 0.0.8.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by negiDharmendra** [comment] 2019-04-03 07:59
@manavghaigithub  it works fine for me. I am on Window 10.
Please share the logs file with us.

## My setup:


VS-Code version: 1.32.3
Gauge Extension Version: 0.0.9

Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.1)
dotnet (0.1.2.nightly-2019-02-14)
html-report (4.0.6)
screenshot (0.0.1)

**Comment by pmcphailWAT** [comment] 2019-04-03 15:10
I'm using Windows 7 and seeing this issue.  I'm able to roll back to the gauge plugin 0.0.8 and it works again. I've attached the log.  I first did a gauge init python and confirmed the issue on 0.0.9 and then rolled back to 0.0.8 and confirmed that the plugin is working as intended.
[lsp.log](https://github.com/getgauge/gauge-vscode/files/3039344/lsp.log)

**Comment by nehashri** [comment] 2019-04-04 09:55
@manavghaigithub @pmcphailWAT I was able to make a fix for this issue. However, can you try this out and let me know if this fix works for you too.
To install the extension, 
- First download the latest nightly version of the Gauge VSCode extension from [here](https://bintray.com/gauge/gauge-vscode/Nightly/0.0.10.nightly-2019-04-04) or https://bintray.com/gauge/gauge-vscode/download_file?file_path=gauge-0.0.10.nightly-2019-04-04.vsix
- You can now installed the downloaded extension. Refer [this](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to install a downloaded extension.

If this fix works, we will look at releasing this extension to the VSCode marketplace.

**Comment by pmcphailWAT** [comment] 2019-04-04 15:41
It looks like 0.0.10 nightly build has resolved the issue

**Comment by nehashri** [comment] 2019-04-05 04:50
@pmcphailWAT Thanks for letting us know

**Comment by pmcphailWAT** [comment] 2019-04-05 15:00
You're welcome, thanks for the quick fix.

**Comment by Debashis9012** [comment] 2019-04-22 08:07
This issue has been verified and found fixed with the ``` 	
gauge-0.0.10.nightly-2019-04-09```

**Closed by Debashis9012** 2019-04-22 08:07 UTC
Labels: ready for QA
