### ISSUE TITLE
Step definitions don't update in spec file autocompletion unless the step implementation file is saved in vs-code

### ISSUE THREAD

**Issue by ConfusedSky** [getgauge/gauge-vscode#360] opened 2019-03-27 21:51 UTC
I use typescript to write my gauge step definitions. Whenever I save my typescript file it transpiles to a javascript file. May also be true for other languages but untested.
# Expected Behaviour
New steps defined in the typescript file should be available for use in spec files
# Actual Behaviour
I need to open the step_implementation.js file and save it to use the new steps in spec files
# Steps to reproduce
1. Generate your step implementation file outside of vs-code (using babel, ts, another script, etc)
2. Without opening step_implementation.js, write one of the new steps that were defined in a spec file.
3. gauge-vscode should tell you there is no step definition for that step
4. open step_implementation.js and force a save
5. Go back to your spec and the error should go away.

# System info

Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.8)
js (2.3.4)
screenshot (0.0.1)

gauge-vscode version 0.0.8

![image](https://user-images.githubusercontent.com/12839429/55114002-0d515680-509e-11e9-85c1-449ec4676ba6.png)

**Comment by shubhamsc** [comment] 2019-03-28 09:20
@ConfusedSky I tried to replicate this issue but it's working for me.
### Steps I followed
1. Create a gauge js project
2. Implements the test is TypeScript.
3. Close VS-Code
3. Tranpile the test in JS with Babel in tests dir from command line.
4. Open vs-code 
I didn't see any error in the spec file.
Can you check these steps? Am I missing something?

It will helpful if you share any sample project where we can reproduce the issue.

**Comment by ConfusedSky** [comment] 2019-03-28 20:41
It works if you close and reload VS-Code, but I have tsc -w running in the background and would rather not have open and close VS-Code every time I make a new change. 

I would prefer if it would watch for changes. Try again without reloading VS-Code.

**Comment by shubhamsc** [comment] 2019-04-01 13:03
@ConfusedSky you are right. if we add anything from outside in the implementation file and it's not open in vs code(not needed as an active file). Gauge doesn't know that something is changed on that file because in this case, vs code doesn't send any changed request to Gauge. Gauge need to read again that file to show reflects what will happen when open that file in vs code or reload the project. 
That means you do not need to forcefully save that file, it just needs to open that file in vs code anywhere while working on that.

**Comment by shubhamsc** [comment] 2019-04-02 15:42
@ConfusedSky Currently Gauge doesn't have a runner for TypeScript. Maybe Transpiling code from TypeScript to JavaScript does not support some action seamlessly in VS Code.

**Comment by shubhamsc** [comment] 2019-04-02 17:40
@ConfusedSky  I'm closing this issue. If you have any question, you can reopen the issue or post your question in gauge [gitter](https://gitter.im/getgauge/chat) channel.

**Comment by ConfusedSky** [comment] 2019-04-03 23:12
I still think it is an issue. Whether or not you can do anything about it right now, it is expected behavior. 

I haven't run into issues like this with other plugins I use. I'm not saying that you should put this as a high priority issue or anything but it still is an issue.

Furthermore, I know it's possible for vs-code to watch the filesystem for changes. So it would be possible to just watch the STEP_IMPL_DIR for changes and update then.

**Comment by zabil** [comment] 2020-08-28 15:36
Closing this as an old issue. However, any PR's to fix this will be merged.

**Closed by zabil** 2020-08-28 15:36 UTC
