### ISSUE TITLE
Current gauge language runner is not compatible with gauge LSP.

### ISSUE THREAD

**Issue by RFEY-test** [getgauge/gauge-vscode#447] opened 2020-09-01 08:04 UTC
see this Error in VScode and some stepimplementation and editing features do not work.
Current gauge language runner is not compatible with gauge LSP. Some of the editing feature will not work as expected

Here is the gauge version information:
gauge version
Gauge version: 1.1.1
Commit Hash: 6e0d83f
Plugins
html-report (4.0.12)
java (0.7.9)
screenshot (0.0.1)
xml-report (0.2.3)

manifest.json:
{
    "Language": "java",
    "Plugins": [
      "html-report",
      "xml-report"
    ]
  }

**Comment by zabil** [comment] 2020-09-01 08:21
This usually happens when there is a compilation error in the Java project. Try to fixing any compilation errors, missing libraries and re-launch. There is a release coming soon that will point to the right error.

**Comment by RFEY-test** [comment] 2020-09-01 11:57
@zabil I don't have any compilation errors. Do you have another idea?

**Comment by sriv** [comment] 2020-09-01 12:21
Do you see any information in the logs? The log files are under `logs` directory, in your project root.

**Comment by RFEY-test** [comment] 2020-09-02 06:15
Oh, you are right, there are multiple errors:
lsp.log:
[Gauge] [ERROR] Unable to add directory to file watcher: GetFileAttributes: Das System kann die angegebene Datei nicht finden.

[Gauge] [ERROR] Error occurred while waiting for runner process to finish.
Error : exit status 1
[Gauge] [DEBUG] unable to connect to runner : Error occurred while waiting for runner process to finish.
Error : exit status 1
Some of the gauge lsp feature will not work as expected.
[Gauge] [INFO] LangServer: reading on stdin, writing on stdout
[Gauge] [ERROR] notif #0: initialized: current runner is not compatible with gauge LSP
[Gauge] [ERROR] Specs directory specs does not exists.

But the specs folder exist...

From these error I have a whole list:
[java] [ERROR] src\main\java\de\xxx\qa\Email.java:9: error: package org.tinylog does not exist
[java] [ERROR] import org.tinylog.Logger;
[java] [ERROR] ^

[Gauge] [ERROR] notif #0: initialized: current runner is not compatible with gauge LSP


gauge.log:
[Gauge] [ERROR] Error occurred while waiting for runner process to finish.
Error : exit status 1
[Gauge] [CRITICAL] Failed to start gauge API: Error occurred while waiting for runner process to finish.
Error : exit status 1

**Comment by RFEY-test** [comment] 2020-09-02 09:14
Btw, the errors only appear on my machine. On the machines from my colleagues everything works fine, also with the same repository when the tests are executed with jenkins. So I would guess it's a configuration issue, but I have no idea what it could be.

**Comment by zabil** [comment] 2020-09-02 11:25
Closing as duplicate of https://github.com/getgauge/gauge-vscode/issues/440 there will be a fix to point out the right error.

**Closed by zabil** 2020-09-02 11:25 UTC

**Comment by RFEY-test** [comment] 2020-09-02 12:12
I don't see how this issue is solved. Even when the error message is wrong, the error is still there. Or do you want me to create another issue just becaue of the title?

**Comment by zabil** [comment] 2020-09-02 12:21
It's not solved but a duplicate of https://github.com/getgauge/gauge-vscode/issues/440 which was raised earlier.

**Comment by RFEY-test** [comment] 2020-09-02 12:25
@zabil fair engough, but your solution in #440 doesn't work for me. If I run gauge init java I get the error 
[Gauge] This is already a Gauge Project. Please try to initialize a Gauge project in a different location.

So it seems the solution is different from #440

**Comment by zabil** [comment] 2020-09-02 12:59
Sorry for not being clear.

The error is the way in how Gauge VS Code plugin handles errors. `Current gauge language runner is not compatible with gauge LSP` is a generic error. The steps in mentioned in #440 is a way to replicate the error. 

However, the issue is related to project configuration of compilation error. So the solution is for the plugin to point to the right error instead of throwing the generic error so. Hopefully, with the right error message a user can know what's wrong and fix the error.

Also, if you can share a project to replicate the error it will help test the fix (Although you did mention it works on other machines)

**Comment by RFEY-test** [comment] 2020-09-03 08:44
@zabil 
thanks for the explanation. It helped me a lot to understand. Unhappily I'm not able to share the code because it's the property of the company I work for. 

Do you have an idea how I can solve this issue on my machine? 

Btw, if I create a project from the scratch with less complexity, it works for me... But that's not the goal 😅

**Comment by RFEY-test** [comment] 2020-09-03 08:47
Also it seems to be not a vs code issue. If I run `gauge run` via poweshell I get the same errors.

**Comment by sriv** [comment] 2020-09-03 08:53
> [Gauge] [ERROR] Unable to add directory to file watcher: GetFileAttributes: Das System kann die angegebene Datei nicht finden.

I am guessing this could be due to file permissions?

Are you able to build your project independent of gauge? ex. if you are using maven, you can try running `mvn test-compile`

If the build goes through fine, can you check if you are able to run the project using the pre-built jars? You can set `GAUGE_CUSTOM_BUILD_PATH=<out dir of build>` and then invoke gauge run.

**Comment by RFEY-test** [comment] 2020-09-04 08:04
@sriv Thanks I think that helped a lot. At least it seems it demasked some other issues, but I think my colleagues can help me with this. 

Thanks again!
