### ISSUE TITLE
.gauge/plugins does not exist when attempting to create a new Gauge project

### ISSUE THREAD

**Issue by jpollone** [getgauge/gauge-vscode#432] opened 2020-05-29 09:40 UTC
**Installation**
As of this issue date/time.

```brew install gauge``` (and brew reinstall gauge)
> ==> Downloading https://homebrew.bintray.com/bottles/gauge-1.0.8.catalina.bottle.tar.gz
Already downloaded: /Users/jpollone/Library/Caches/Homebrew/downloads/f53f7053f505d8010d5a7d2761fd075cfc9656d315cb4ad1e1ff0da64746593f--gauge-1.0.8.catalina.bottle.tar.gz
==> Reinstalling gauge
==> Pouring gauge-1.0.8.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/gauge/1.0.8: 3 files, 17.5MB

```code --install-extension getgauge.gauge```
> Installing extensions...
Installing extension 'getgauge.gauge' v0.0.13...
Extension 'getgauge.gauge' v0.0.13 was successfully installed.

**Run in VS Code**
```Gauge: Create a new Gauge project```

**VS Code errors**

> Command 'Gauge: Create a new Gauge Project' resulted in an error (command 'gauge.createProject' not found)

> Error fetching Gauge and plugins version information. error: open /Users/jpollone/.gauge/plugins: no such file or directory { "version": "1.0.8", "commitHash": "", "plugins": [] }

**Verification**
I verified ```~/.gauge/plugins``` does not exist but ```~/.gauge/config``` exists

**Version info**
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0 (Catalina 10.15.5)

**Comment by sriv** [comment] 2020-05-29 10:07
Seems like a duplicate of #431, which is fixed via https://github.com/getgauge/gauge/pull/1651

we'll be releasing a new version of gauge soon.

**Closed** 2020-05-29 10:21 UTC
