### ISSUE TITLE
Set launch configuration in VSC (Python-plugin)

### ISSUE THREAD

**Issue by jensakejohansson** [getgauge/gauge-vscode#353] opened 2019-02-13 08:20 UTC
When I run a test from within VSC (Python-plugin) Gauge starts like this:
```Running tool: gauge run c:\path_to\specs\my.spec:7 --simple-console --hide-suggestion```
How can I change this launch string? I want to specify a special property-file when I run locally in the IDE. I want something like this:
```Running tool: gauge run c:\path_to\specs\my.spec:7 --simple-console --hide-suggestion --env "local, default"```
I don't see that this is possible to achieve at the moment? Thanks.

**Comment by zabil** [comment] 2019-02-13 09:13
For setting environments I recommend an action in VS Code's command palette called `Gauge: Set Environment' which will list all the environments. You can select one or more environments. Running specifications will use the selected environments.

VS Code's status bar will display the selected environment for reference.

**Comment by jensakejohansson** [comment] 2019-02-13 09:58
![bild](https://user-images.githubusercontent.com/12295087/52703206-1bc83080-2f7e-11e9-8c32-478fcc457fe4.png)

That would be nice, but I don't seem to have that option? Running Gauge 0.0.8 in a Python project.

**Comment by zabil** [comment] 2019-02-13 11:48
Sorry for not being clear enough.
We haven't implemented this feature yet!

**Comment by jensakejohansson** [comment] 2019-02-13 11:54
Ah, sorry, now I understand. Your suggestion sounds good though 👍

**Comment by delmaamoun** [comment] 2019-05-31 12:20
It would be nice to modify the run command. For example, it makes more sense to me when running the tests from vscode to have them as verbose to monitor the run. would something like that be possible @zabil ?

**Comment by zabil** [comment] 2019-06-04 10:17
Unfortunately at this is not possible at the moment.

**Comment by NeilCross** [comment] 2019-09-20 02:16
@jensakejohansson: if you set the ENV environment variable then launch vscode, this value will be used for the environment when launching gauge with this plugin.

**Comment by CharlieDigital** [comment] 2020-11-03 00:36
@NeilCross how can one set the ENV variable?

I have the same need as @jensakejohansson but perhaps a different use case (different team members would like to have different URLs when they click on "Run Spec" or "Run Scenario" within VS Code).

Have not yet found a way to make this work.

**Comment by zabil** [comment] 2020-11-23 10:11
This issue is a duplicate of https://github.com/getgauge/gauge-vscode/issues/289

**Closed by zabil** 2020-11-23 10:11 UTC
Labels: community, triage
