### ISSUE TITLE
The Gauge server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by manishranjan-alation** [getgauge/gauge-vscode#305] opened 2018-11-16 10:26 UTC
Expected behavior
User should be able to seamlessly use vscode

Actual behavior
Getting the error message and gauge stops working.
Specs don't work.

Steps to replicate

Open a gauge-python project in VSCode
Ensure my-python.python is 2018.10.1
Gauge version 0.0.7
Copy and page any step.

**Comment by nehashri** [comment] 2018-11-19 05:51
@manishranjan-alation This seems to work fine for me. Can you please provide a little more details on the Gauge version and plugins version you are using. You can run `gauge -v` on the command line and paste its contents here. 
Can you also specify your python version and the `getgauge` pypi package version. To get the getgauge pypi package version, you can run `pip show getgauge` or `pip3 show getgauge` accordingly.

**Comment by manishranjan-alation** [comment] 2018-11-19 05:56
Please find the required details below @nehashri 
Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
html-report (4.0.6)
python (0.3.4)
screenshot (0.0.1)
spectacle (0.1.3)

pip show getgauge
Name: getgauge
Version: 0.3.4

Python version: Python 2.7.10

**Comment by nehashri** [comment] 2018-11-21 05:20
@manishranjan-alation I don't seem to be able to replicate this on my Mac. Can you let us know which OS you are on. Also, I see that your Gauge version is quite old, have you considered [updating Gauge](https://docs.gauge.org/latest/installation.html) and check if it solves your issue.

**Comment by manishranjan-alation** [comment] 2018-11-21 07:36
@nehashri Mac Os Mojave 10.14.1 (18B75) 
I was using the latest gauge and was facing the same issue then I tried downgrading it and the issue still exists. VSCode Version 1.29.1 (1.29.1).

**Comment by nehashri** [comment] 2018-11-21 08:05
Can you check logs/lsp.log file in your gauge project and see if any errors are reported there?

**Comment by manishranjan-alation** [comment] 2018-11-21 11:02
@nehashri These are the logs coming in lsp.log file when the crash happens. No particular error log is coming up.
Spec file added / modified:/Users/manish.ranjan/Documents/aaaa/bbbbb/cccc/specs/dddddd/eeeeee/fffffff.spec
Unable to connect to runner : Timed out connecting to python
Some of the gauge lsp feature will not work as expected.
LangServer: reading on stdin, writing on stdout

**Comment by Apoorva-GA** [comment] 2018-11-30 06:54
@manishranjan-alation I am unable to replicate the issue. If you are still facing this issue, Please share a sample project where the issue is replicable.

**Comment by manishranjan-alation** [comment] 2018-11-30 07:07
After the crash, specs are executed from the terminal successfully but nothing works in UI. Run/Debug configuration options are missing. We can not switch between specs, concepts, and step implementation.  
This is happening for all the projects either, we create a new one or import an existing project.

**Comment by sguptatw** [comment] 2018-11-30 07:15
@manishranjan-alation Can you give us more details about when it crashes.
Does it crash on
- loading the project
- editing a specification
- editing a code implementation
- autocomplete of a step
- goto definition
....

It will help us replicate investigate further.

**Comment by manishranjan-alation** [comment] 2018-11-30 07:31
[tets-gauge.zip](https://github.com/getgauge/gauge-vscode/files/2632412/tets-gauge.zip)
 
This is a sample project and getting the issue here as well.

**Comment by sguptatw** [comment] 2018-11-30 07:39
@manishranjan-alation Can u plz give us the details by executing the command `gauge config --list`

**Comment by manishranjan-alation** [comment] 2018-11-30 07:40
manish-ranjan-macbook-pro:tets-gauge manish.ranjan$ gauge config --list
Key                             Value
--------------------------------------------------------------------
gauge_update_url                https://downloads.gauge.org/gauge
runner_connection_timeout       30000
plugin_kill_timeout             4000
runner_request_timeout          30000
gauge_telemetry_enabled         true
gauge_repository_url            https://downloads.gauge.org/plugin
gauge_templates_url             https://downloads.gauge.org/templates
plugin_connection_timeout       10000
ide_request_timeout             30000
check_updates                   true
gauge_telemetry_log_enabled     false

**Comment by manishranjan-alation** [comment] 2018-11-30 10:43
@Apoorva-GA Tried. Got the same result.

Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
html-report (4.0.6)
python (0.3.5.nightly-2018-10-31)
screenshot (0.0.1)
spectacle (0.1.3)

**Comment by Apoorva-GA** [comment] 2018-11-30 10:58
@manishranjan-alation Your gauge version still shows 1.0.0. Please update to the latest.

**Comment by manishranjan-alation** [comment] 2018-11-30 11:22
@Apoorva-GA After upgrading the gauge version, vscode worked fine, run and debug option was coming. But after some time it crashed again with the same message as before.

**Comment by Apoorva-GA** [comment] 2018-11-30 11:47
One last thing to try, Can you try by updating to the latest Gauge-VSCode extension as well https://bintray.com/gauge/gauge-vscode/Nightly/0.0.8.nightly-2018-11-27.

Kindly note to do this : even if the extension is removed from Vscode, it has to be manually deleted from the vscode extensions folder. Which is located at `~/.vscode`

**Comment by manishranjan-alation** [comment] 2018-11-30 14:04
@Apoorva-GA Cleared everything and then installed gauge extension, still getting the same issue.

**Comment by sguptatw** [comment] 2018-11-30 14:06
@manishranjan-alation Can you please confirm what your current gauge extension version is.

**Comment by sguptatw** [comment] 2018-11-30 14:11
@manishranjan-alation Just wanted to re-confirm. Did you use the Install from VSIX option to install the nightly downloaded from https://bintray.com/gauge/gauge-vscode/Nightly/0.0.8.nightly-2018-11-27?

Can you please confirm what your current gauge extension version is.

**Comment by manishranjan-alation** [comment] 2018-11-30 14:12
<img width="1383" alt="screen shot 2018-11-30 at 7 38 19 pm" src="https://user-images.githubusercontent.com/44355697/49294049-db592a80-f4d7-11e8-9f38-b8424c0b7b0b.png">
Gauge extension version 0.0.8(screenshot attached)
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
html-report (4.0.6)
python (0.3.5.nightly-2018-10-31)
screenshot (0.0.1)
spectacle (0.1.3)

**Comment by singharsh** [comment] 2019-01-27 01:55
+1
Facing this issue since quite some time.
Any plans on a fix or workaround?

**Comment by sriv** [comment] 2019-01-28 02:30
hi @manishranjan-alation, @singharsh - we do plan to fix it, but so far we have been unsuccessful in replicating this.

My theory (from below observartion) is that there is probably some firewall or rule blocking the connection between gauge and the runner.

- noted from `lsp.log` from [above sample project](https://github.com/getgauge/gauge-vscode/issues/305#issuecomment-443116800): `Unable to connect to runner : Timed out connecting to python`

Logs when I open the project:

```
07:45:06.773 Initializing concepts cache with 0 concepts
07:45:06.773 Watching directory: /tmp/vscode-issue/tets-gauge/specs
07:45:06.773 Found 1 files
07:45:06.778 Initializing specs cache with 1 specs
07:45:06.778 Adding specs from /tmp/vscode-issue/tets-gauge/specs/example.spec
07:45:06.778 Initializing steps cache with 1 steps
07:45:06.778 "POST /collect HTTP/1.1\r\nHost: www.google-analytics.com\r\nUser-Agent: Go-http-client/1.1\r\nContent-Length: 159\r\nContent-Type: application/x-www-form-urlencoded\r\nAccept-Encoding: gzip\r\n\r\naip=1&an=Gauge+Core&av=1.0.4&cid=8394686e-47d2-4012-a272-76837993d127&cm=console&cs=Gauge+Core&ea=lsp&ec=daemon&el=python%!C(MISSING)linux&t=event&tid=UA-54838477-1&v=1"
07:45:06.779 Starting language runner
07:45:18.158 Python: 2.7.15rc1
07:45:18.172 Listening on port:35733
07:45:18.172 LangServer: reading on stdin, writing on stdout
```

Logs from your project:
```
12:11:04.787 LangServer: reading on stdin, writing on stdout
12:11:05.080 Watching directory: /Users/manish.ranjan/Documents/SelfTest/tets-gauge/specs
12:11:05.080 Found 1 files
12:11:05.081 Initializing concepts cache with 0 concepts
12:11:05.082 Initializing specs cache with 1 specs
12:11:05.082 Adding specs from /Users/manish.ranjan/Documents/SelfTest/tets-gauge/specs/example.spec
12:11:05.082 Initializing steps cache with 1 steps
12:11:05.083 Starting language runner
12:11:35.088 Unable to connect to runner : Timed out connecting to python
Some of the gauge lsp feature will not work as expected.
```

I am afraid that this might be related to your development environment. I think we could add more logs to gauge+vscode, if you have any hints - it'll be very helpful!

**Comment by singharsh** [comment] 2019-01-28 02:46
In my case, specs just work as fine from command line. It's the concepts that don't recognize step implementations and throw several "Step implementation not found" errors.
I wonder if the vscode plugin can't find implementations then how is gauge-python able to run my specs.

**Comment by zabil** [comment] 2019-12-04 11:33
Closing this for now as other python users have not reported this issue in a while. Please feel free re-open it if it happens again.

**Closed by zabil** 2019-12-04 11:33 UTC
Labels: triage
