### ISSUE TITLE
Error when clicking on References annotation on the Steps file

### ISSUE THREAD

**Issue by deepabgit** [getgauge/gauge-vscode#555] opened 2021-01-07 17:22 UTC
Get the following error when clicking references in the Steps file:

**failed to parse request json: cannot unmarshal array into Go value of type string**

Gauge Extension is 0.0.19
Visual Studio Code is 1.52.1

Is the issue related to visual studio code update or gauge extension? How can I fix this issue?

Thanks,
Deepa

**Comment by deepabgit** [comment] 2021-01-07 20:07
Please find attached a screenshot that may help in understanding my issue:

![image](https://user-images.githubusercontent.com/72279222/103939564-d0bee580-50e0-11eb-8ad4-306e90dc32fe.png)

**Comment by zabil** [comment] 2021-01-08 09:18
As mentioned in the issue template can you please fill the following sections.

#### Gauge (Output of `gauge -v`)

#### Node.js/Java/Python/.Net/Ruby version

#### Operating System information

This issue will be re-opened you submit the info as a comment.

**Comment by deepabgit** [comment] 2021-01-08 17:02
**gauge -v**
Gauge version: 1.1.1
Commit Hash: 6e0d83f
Plugins

html-report (4.0.12)
js (2.3.14)
screenshot (0.0.1)
ts (0.1.0)

**Node.js/Java/Python/.Net/Ruby version**
Node.js v12.18.2

**Operating System information**
Windows 10

**Comment by zabil** [comment] 2021-01-08 18:15
Please upgrade Gauge to 1.1.6 and Gauge js plugin to 2.3.15 and see if you still see the same error.

**Comment by deepabgit** [comment] 2021-01-08 19:08
I did and I still see the same issue.  FYI, we are also using another extension - gauge-ts for using typscript.

![image](https://user-images.githubusercontent.com/72279222/104054355-ca447280-51a1-11eb-8264-87128b6d8efe.png)

**Comment by BugDiver** [comment] 2021-01-15 10:36
Duplicate of getgauge/gauge#1857

**Closed** 2021-01-15 10:36 UTC
Labels: needs-more-info
