### ISSUE TITLE
Unable to run or debug scenario via CodeLens with extension version 0.0.16.

### ISSUE THREAD

**Issue by raweaver** [getgauge/gauge-vscode#500] opened 2020-10-30 15:21 UTC
# Describe the bug
Unable to run or debug scenario (or specification) via CodeLens with the latest extension (0.0.16). Was able to run the via CodeLens with the prior version (0.0.15). Any help would be greatly appreciated. Thank you!

### What command(s) did you run when you found the bug?

Clicked on Run Scenario in the spec file in VS Code. Also tried clicking the Debug Scenario, Run Spec and Debug Spec code lens. I also tried navigating to the Test > Gauge Specs window and clicked the green arrow, but same result.

I then executed 'gauge run specs' and it executed the specification successfully.

### Output, stack trace or logs related to the bug

When running one of the example scenarios via CodeLens, I get the following output:

Running tool: gauge run --simple-console --hide-suggestion
C:\Users\me\AppData\Roaming\gauge\plugins\dotnet\0.2.0>dotnet bin\Gauge.Dotnet.dll --start
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  failed to initialize suite datastore. Error: Exception was thrown by handler.
Successfully generated html-report to => c:\_dev\gauge\example\reports\html-report\index.html

Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped

Total time taken: 245ms
Updates are available. Run `gauge update -c` for more info.
Success: Tests passed.

### Versions
Gauge version: 1.1.4
Commit Hash: c982558

Plugins
-------
csharp (0.10.6)
dotnet (0.2.0)
html-report (4.0.12)
java (0.7.10)
js (2.3.12)
python (0.3.11)
ruby (0.5.4)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

#### Operating System information
Windows 10 Enterprise (1803)

#### IDE information
Visual Studio Code
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by NivedhaSenthil** [comment] 2020-11-06 09:18
duplicate of https://github.com/getgauge/gauge-vscode/issues/499

**Closed by NivedhaSenthil** 2020-11-06 09:18 UTC
