### ISSUE TITLE
Getting code lens request timeouts during debug

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#160] opened 2018-03-01 05:42 UTC
**Expected behavior**
Should not get request timeouts while debugging

**Actual behavior**
Getting request timeout
```
Request textDocument/codeLens failed.
  Message: Request timed out for Message with ID => 13 and Type => StepPositionsRequest
  Code: 0 
```

**Suggested behavior**
Code lens need not work during debugging

**Steps to replicate**
* Start debugging a python project
* On a breakpoint wait for a while
> Note the error was observed on Windows

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-28
Commit Hash: d997b9a

Plugins
-------
python (0.2.4.nightly-2018-02-28)
```
Bug on story - https://github.com/getgauge/gauge-python/issues/33

**Comment by Apoorva-GA** [comment] 2018-03-26 10:26
Is this still an issue? Wasn't able to reproduce on windows.

**Comment by Apoorva-GA** [comment] 2018-03-27 08:56
Duplicate of https://github.com/getgauge/gauge/issues/923.
Closing this.

**Closed by Apoorva-GA** 2018-03-27 08:56 UTC
Labels: bug, ready
