### ISSUE TITLE
Rename or refactor a step in a specification or concept

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#81] opened 2017-12-19 09:12 UTC
### Current behavior

F2 or "Rename symbol" does not work for steps inside a specification

### Expected functionality

Use F2 or "Rename Symbol" to refactor a step or concept. When a step is changed it must
* Re-factor the implementation method with the modified step text.
* Re-factor the usages of a concept in all step files.

**Comment by nehashri** [comment] 2018-01-31 11:33
Should be available in gauge nightly version >= 24-01-2018, gauge-vscode >= 30-01-2018, gauge-js >=  15-01-2018

**Comment by sguptatw** [comment] 2018-02-02 09:00
**Test case**
If refactoring is unsuccessful then it should not change specification or the impl file

**Actual behavior**
The specification gets changed

**Steps to replicate**
* In VSCode - `Vowels in English language are "aeiou"` to `Vowels in English language are "aeiousdf" <file:specs/something>`
> Note: specs/something is a valid file

Refactoring fails - It changes the spec file content

**Comment by sguptatw** [comment] 2018-02-02 09:04
**Test case**
Refactoring should not cause a compilation failure

**Actual behavior**
The parameter name generated after refactoring takes the value given in the text as the parameter name. This causes compilation errors sometimes

**Steps to replicate**
* In a `gauge-js` project
* Refactor `Vowels in English language are "aeiou"` to `Vowels in English language are "aeiou" something else "" and "ddd"`
* Goto the implementation files and see the compilation errors

**Comment by sguptatw** [comment] 2018-02-02 09:09
**Test case**
The errors of refactoring should be indicated

**Actual behavior**
No result is displayed

**Steps to replicate**
* In a `gauge-js` project
* Refactor `Vowels in English language are "aeiou"` to an empty step. This should display the reason why refactoring failed clearly.
Currently the output pane shows the error
```
Request textDocument/rename failed.
  Message: Refactoring failed due to errors:
:2 Step should not be blank => ''
  Code: 0 
```
However the IDE gives `No result` on the step.

**Comment by sguptatw** [comment] 2018-02-02 09:18
**Test case**
Gauge does not support Refactoring an alias. This should not trigger refactoring

**Actual behavior**
It is changing the spec but no refactoring occurs

**Steps to replicate**
* Create a step with alias
* Try refactoring it. It changes spec and implementation file remains as is.

**Comment by sguptatw** [comment] 2018-02-02 09:25
**Test case**
When an inline table parameter is present while refactoring

**Actual behavior**
The value of the inline table is replaced with <table> in the refactored text

**Steps to replicate**
* Consider an `unimplemented` step
```
* The word <table> has "3" vowels \ sdfdsf
|sdfsdf|
|sdfsdf|
```
* Try refactoring to `The word <table> has "3" vowels \ sdf` in IDE.
* This replaces step with 
```
The word <table> has "3" vowels \ sdf <table>
```

**Comment by nehashri** [comment] 2018-02-02 09:47
> **Test case**
> If refactoring is unsuccessful then it should not change specification or the impl file

- https://github.com/getgauge/gauge-vscode/issues/81#issuecomment-362526160
Unable to replicate.


> **Test case**
> Refactoring should not cause a compilation failure

- https://github.com/getgauge/gauge-vscode/issues/81#issuecomment-362527296
Seems to be an issue with Gauge-js as behaviour is replicable when executed from command line too!!

> **Test case**
> Gauge does not support Refactoring an alias. This should not trigger refactoring

- https://github.com/getgauge/gauge-vscode/issues/81#issuecomment-362530691
Seems to be an issue with Gauge-js as behaviour is replicable when executed from command line too!!

> **Test case**
When an inline table parameter is present while refactoring

- https://github.com/getgauge/gauge-vscode/issues/81#issuecomment-362532516
Please provide more information to reproduce this issue.

**Comment by sguptatw** [comment] 2018-02-05 03:28
**Blockers for the story**
* Refactoring should not leave the project in a state where user cannot proceed with other actions
- With a script error https://github.com/getgauge/gauge-js/issues/104 other actions are getting affected.

* Refactoring should not change the specifications if runner is not able to complete the action - https://github.com/getgauge/gauge/issues/932.
This is a usability issue

* If Refactoring cannot be performed, the reason should be indicated to the user - https://github.com/getgauge/gauge-vscode/issues/122

* If refactoring of a step cannot be performed, then the action should not be triggered
https://github.com/getgauge/gauge/issues/933

**Out of scope**
- Refactoring with keyword table - https://github.com/getgauge/gauge/issues/934

**Comment by sguptatw** [comment] 2018-05-31 12:03
Retaining the cursor position will be tracked as a part of https://github.com/getgauge/gauge/issues/1062

**Closed by sguptatw** 2018-05-31 12:03 UTC
Labels: ready for QA, refactoring
