### ISSUE TITLE
Error report link does not jump to the appropriate line in implementation

### ISSUE THREAD

**Issue by mojito317** [getgauge/gauge-vscode#408] opened 2019-11-12 13:33 UTC
I wanted to navigate directly to my Python implementation using the links in the report which were logged by the plugin, but unfortunately it did not navigate to the appropriate line.

Steps to reproduce this bug:
-  Run a scenario/spec with the help of the plugin links: <img width="300" alt="Screenshot 2019-11-12 at 14 10 00" src="https://user-images.githubusercontent.com/17944122/68674303-e6c12c80-0555-11ea-8966-ca2c17cf9c1c.png">
-  Check the run report
-  Go to the source of failure by clicking on the link in the report with`⌘+Click` <img width="600" alt="Screenshot 2019-11-12 at 14 13 26" src="https://user-images.githubusercontent.com/17944122/68674842-effec900-0556-11ea-944e-e0f606b66c91.png">
- Cursor is not visible in the reported line but in the line the file was previously left (or in the default setting) <img width="859" alt="Screenshot 2019-11-12 at 14 17 25" src="https://user-images.githubusercontent.com/17944122/68675102-787d6980-0557-11ea-8b28-3d8f642ef930.png">

I am working on MacOS Mojave 10.14.6
Gauge plugin version: 0.0.10
VSCode version: 1.37.1

**Comment by BugDiver** [comment] 2019-11-13 05:54
@mojito317 I was able to replicate the issue. The issue is that the stack trace does not contain the line no in a proper format which vs code could understand.

**Comment by Apoorva-GA** [comment] 2019-11-25 08:13
I have raised a [issue](https://github.com/microsoft/vscode/issues/85174) in VSCode initially and moved the [same](https://github.com/microsoft/vscode-python/issues/8754) to python extension on suggestion from VSCode

**Comment by mojito317** [comment] 2019-12-01 15:38
@Apoorva-GA Thank you!

**Comment by zabil** [comment] 2020-08-28 15:39
Closing this as it's an upstream bug and they have voted not to fix it. https://github.com/microsoft/vscode/issues/85476#issuecomment-599291921

**Closed by zabil** 2020-08-28 15:39 UTC
Labels: waiting-for-upstream
